#!/usr/bin/env bash
# To check for command line argument

if  [ $# -lt 4 ]
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

# Parameters to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Strict host key checking being disabled

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"


# checking if the transfer goes smooth

if [ $? -eq 0 ]
        echo "SUCESSES FILE TRANSFERED"
else
        echo "FILE TRANSFER WENT WRONG"
fi
