#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

	echo "Hello world!" | sudo tee /var/www/html/index.html
	echo "Hello World!" |sudo tee  /var/www/html/index.nginx-debian.html
# Conducting a test

sudo nginx -t

sudo service nginx reload
