#!/usr/bin/env bash

# Configure Nginx to include custom headers (on web-01 and web-02)
var=$(hostname)
config_file="/etc/nginx/sites-available/default"
custom_404="error_page 404 /custom_404.html;\n location /redirect_me {\n return 301 \$scheme://www.google.com;"
served_by="server {\n\tadd_header X-Served-By $var;"

# Update and install Nginx
apt-get update -y
apt-get install nginx -y

# Create default index.html
echo "Hello World!" > /usr/share/nginx/html/index.html

# Create custom 404 page
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure Nginx
sudo sed -i -E "s/^[^#]+location \/ {$/$custom_404/" "$config_file"
sudo sed -i -E "s/^server {$/$served_by/" "$config_file"

# Start Nginx service
sudo service nginx start
